Fix KERNEL_OUTPUT for cmd_ssh and cmd_gdb, add verbose option

diff --git a/ktest b/ktest
--- a/ktest
+++ b/ktest
@@ -45,38 +45,6 @@ cmd_run()
 	echo "	-j	j option to make"
     }
 
-    while getopts "hKb:k:i:t:j:" arg; do
-	case $arg in
-	    h)
-		run_usage
-		exit 0
-		;;
-	    k)
-		KERNEL_SOURCE=`realpath "$OPTARG"`
-		;;
-	    K)
-		BUILD=""
-		;;
-	    i)
-		IMG=$OPTARG
-		;;
-	    t)
-		TIMEOUT=$OPTARG
-		;;
-	    b)
-		KERNEL_OUTPUT=$OPTARG
-		;;
-	    j)
-		NJOBS=$OPTARG
-		;;
-	esac
-    done
-    shift $(( OPTIND - 1 ))
-
-    if [ ! -n "$KERNEL_OUTPUT" ] ; then
-       KERNEL_OUTPUT="$KERNEL_SOURCE/$DIR"
-    fi
-
     kconfig="$KERNEL_OUTPUT/.config"
     config_tool="$KERNEL_SOURCE/scripts/config"
 
@@ -146,25 +114,26 @@ cmd_run()
 	FILES+=" `realpath $req`"
     done
    
-    sudo rm -rf container
-    for req in $CONTAINER; do
-        mkdir -p container
-	if [ ! -e "$req" ]; then
-	    echo "Container $req not found"
-	    exit 1
+    if [ -n "$CONTAINER" ]; then
+	sudo rm -rf container
+	for req in $CONTAINER; do
+	    mkdir -p container
+	    if [ ! -e "$req" ]; then
+		echo "Container $req not found"
+		exit 1
+	    fi
+	    cname=`basename "$req" .tar.gz`
+	    sudo tar xz -C container -f "$req"
+	    if [ ! -d "container/$cname" ] ; then
+		echo "Container '$req' does not unpack into expected directory '$cname'"
+		exit 1
+	    fi
+	done
+	if [ -d container ] ; then
+	    FILES+=" container"
+	    NEED_SUDO=sudo
 	fi
-        cname=`basename "$req" .tar.gz`
-        sudo tar xz -C container -f "$req"
-        if [ ! -d "container/$cname" ] ; then
-           echo "Container '$req' does not unpack into expected directory '$cname'"
-           exit 1
-        fi
-    done
-    if [ -d container ] ; then
-	FILES+=" container"
-        NEED_SUDO=sudo
     fi
-
 
     if [ -n "$BUILD" ]; then
 	[ -f "$kconfig" ] || cp "$KTESTDIR/defconfig" "$kconfig"
@@ -268,6 +237,41 @@ if [ -z "$1" -o "`type -t "$CMD"`" != "function" ]; then
 fi
 shift
 
+while getopts "hKb:k:i:t:j:v" arg; do
+    case $arg in
+	h)
+	    run_usage
+	    exit 0
+	    ;;
+	k)
+	    KERNEL_SOURCE=`realpath "$OPTARG"`
+	    KERNEL_OUTPUT="$KERNEL_SOURCE/$DIR"
+	    ;;
+	K)
+	    BUILD=""
+	    ;;
+	i)
+	    IMG=$OPTARG
+	    ;;
+	t)
+	    TIMEOUT=$OPTARG
+	    ;;
+	b)
+	    KERNEL_OUTPUT=$OPTARG
+	    ;;
+	j)
+	    NJOBS=$OPTARG
+	    ;;
+	v)
+	    set -x
+	    ;;
+    esac
+done
+shift $(( OPTIND - 1 ))
+
+if [ -z "$KERNEL_OUTPUT" ]; then
+    KERNEL_OUTPUT="$KERNEL_SOURCE/$DIR"
+fi
 
 if [ -d "$HOME/.ktest/tmp" ]; then
     TMPDIR=$HOME/.ktest/tmp
@@ -275,7 +279,6 @@ else
     TMPDIR=/tmp
 fi
 
-set -x
 checkdep realpath
 checkdep genisoimage
 checkdep minicom
