testy: Print out failures correctly when running all tests
Change-Id: Ie325d39d0ae297b2d9e09b8e7d8d7791969136a9

diff --git a/testy b/testy
--- a/testy
+++ b/testy
@@ -161,12 +161,14 @@ if [ "$DRYRUN" == 0 ]; then
     for testfile in $tests_to_run; do
         testname=$(basename "$testfile")
 	starttime=$(date +%s)
+	failed=0
 
-	run_test "$testfile" > "/tmp/$testname.log" 2>&1 || ret=1
+	run_test "$testfile" > "/tmp/$testname.log" 2>&1 || failed=1
 
 	duration=$(($(date +%s) - starttime))
 
-	if [ $ret = 1 ]; then
+	if [ $failed = 1 ]; then
+	    ret=1
 	    sed "s/^/[$testname] /" "/tmp/$testname.log"
 	    echo "[$testname] FAILURE: test finished at $(date +%s) -- $(date) after $duration seconds"
 	    [ $KEEP_GOING = 0 ] && break
